name: Deploy to Yandex Cloud Storage

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS CLI for Yandex Cloud
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.YC_SERVICE_ACCOUNT_KEY_ID }}
          aws-secret-access-key: ${{ secrets.YC_SERVICE_ACCOUNT_SECRET }}
          aws-region: ru-central1
          custom-endpoint-url: https://storage.yandexcloud.net

      - name: Upload files to Yandex Storage
        run: |
          aws s3 sync ./ s3://${{ secrets.YC_BUCKET_NAME }} --delete --acl public-read